### PR TITLE
 jweixin-jssdk update to 1.3.2

### PR DESCRIPTION
**Pull request by LazyNeo**
版本更新

### CODE REVIEW

**Comment by yanxi-me** [comment]
谢谢~

**Comment by LazyNeo** [comment]
感谢大佬在我迷茫的时候提供了这个npm库，当时找了好久，也不知道要怎么玩。
大佬，要不把npm包也顺便更新下吧

**Comment by yanxi-me** [comment]
已经更新：weixin-js-sdk@1.3.2  请试试这个版本，有问题别忘了告诉我。

**Comment by LazyNeo** [comment]
ok




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            neo
                            
                            
                                
                                    邮箱：535178368@qq.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年02月07日 11:43，Yanxi 写道： 已经更新：weixin-js-sdk@1.3.2  请试试这个版本，有问题别忘了告诉我。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yanxi-me/weixin-js-sdk","title":"yanxi-me/weixin-js-sdk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yanxi-me/weixin-js-sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yanxi-me in #15: 已经更新：weixin-js-sdk@1.3.2  请试试这个版本，有问题别忘了告诉我。"}],"action":{"name":"View Pull Request","url":"https://github.com/yanxi-me/weixin-js-sdk/pull/15#issuecomment-363647342"}}}

**Pull request merged**
